FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build




FROM node:20-alpine
WORKDIR /app



# Устанавливаем serve для раздачи статических файлов
RUN npm install -g serve

# Копируем собранные файлы из стадии build
COPY --from=build /app/dist /app/dist

CMD ["serve", "-s", "dist", "-l", "5173"]
