services:
  bot:
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
    env_file:
      - ./backend/.env
    command: ["node", "bot.js"]
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
    env_file:
      - ./backend/.env
    ports:
      - "8200:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-frontend
    env_file:
      - ./frontend/.env
    networks:
      - app-network

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
